{{/*
Copyright 2019-present Open Networking Foundation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- $configJson := index .Values.config.mme.cfgFiles "config.json" }}
{{- $configJsonS11 := index $configJson "s11" }}
{{- $configJsonS1ap := index $configJson "s1ap" }}
---
apiVersion: v1
kind: Service
metadata:
  name: mme-s11
  labels:
{{ tuple "mme" . | include "omec-control-plane.metadata_labels" | indent 4 }}
spec:
  selector:
{{ tuple "mme" . | include "omec-control-plane.metadata_labels" | indent 4 }}
{{- if .Values.config.mme.s11.nodePort.enabled }}
  type: NodePort
{{- end }}
  ports:
  - name: s11
    port: {{ index $configJsonS11 "egtp_default_port" }}
    protocol: UDP
  {{- if .Values.config.mme.s11.nodePort.enabled }}
    nodePort: {{ .Values.config.mme.s11.nodePort.port }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: mme-s6a
  labels:
{{ tuple "mme" . | include "omec-control-plane.metadata_labels" | indent 4 }}
{{- if .Values.config.mme.s6a.nodePort.enabled }}
  type: NodePort
{{- end }}
spec:
  selector:
{{ tuple "mme" . | include "omec-control-plane.metadata_labels" | indent 4 }}
  ports:
  - name: s6a
    port: 3868
    protocol: TCP
  {{- if .Values.config.mme.s6a.nodePort.enabled }}
    nodePort: {{ .Values.config.mme.s6a.nodePort.port }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: mme-s1ap
  labels:
{{ tuple "mme" . | include "omec-control-plane.metadata_labels" | indent 4 }}
spec:
  selector:
{{ tuple "mme" . | include "omec-control-plane.metadata_labels" | indent 4 }}
  type: NodePort
  ports:
    - name: s1ap
      port: {{ index $configJsonS1ap "sctp_port" }}
      nodePort: {{ index $configJsonS1ap "sctp_port_external" }}
      protocol: SCTP
