# Copyright 2018-present Open Networking Foundation
# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

images:
  tags:
    omecCni: docker.io/omecproject/omec-cni:0.0.1
    sriovDp: docker.io/nfvpe/sriov-device-plugin:v3.0.0
  pullPolicy: IfNotPresent

# We need to speficy both pfName and driver name to prevent one interface to be
# allocated to multiple resource pools
resourceList:
  - resourceName: sriov_vfio
    # Provide vfio-pci bounded physical function names in your cluster under "pfNames"
    # Do not change "drivers" unless you know what you're doing
    selectors:
      pfNames:
        - eno1
      drivers:
        - vfio-pci
  - resourceName: sriov_netdevice
     # Provide pfNames and their drivers that serve virtual functions in your cluster
    selectors:
      pfNames:
        - eno1
      drivers:
        - ixgbevf
