---

# Copyright 2018-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: exampleservice
data:
  service-config: |
    name: exampleservice
    accessor:
      username: {{ .Values.xos.admin_user }}
      password: {{ .Values.xos.admin_password }}
      endpoint: xos-core:50051
    required_models:
      - ExampleService
      - ExampleServiceInstance
      - ServiceDependency
      - ServiceMonitoringAgentInfo
    dependency_graph: "/opt/xos/synchronizers/exampleservice/model-deps"
    steps_dir: "/opt/xos/synchronizers/exampleservice/steps"
    sys_dir: "/opt/xos/synchronizers/exampleservice/sys"
    model_policies_dir: "/opt/xos/synchronizers/exampleservice/model_policies"
    models_dir: "/opt/xos/synchronizers/exampleservice/models"
