apiVersion: v1
kind: Secret
metadata:
  name: coreapi-cert-secret
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.core_api_cert }}
  tls.key: {{ .Values.secrets.core_api_key }}
