# Copyright 2018-present Open Networking Foundation
# Copyright 2018 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

images:
  tags:
    init: docker.io/omecproject/pod-init:0.1.0
    hssdb: docker.io/omecproject/c3po-hssdb:0.1.0-dev
    hss: docker.io/omecproject/c3po-hss:0.1.0-dev
    mme: docker.io/omecproject/openmme:0.1.0-dev
    spgwc: docker.io/omecproject/ngic-cp:0.1.0-dev
    depCheck: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
  pullPolicy: IfNotPresent

nodeSelectors:
  enabled: false
  hss:
    label: omec-cp
    value: enabled
  mme:
    label: omec-cp
    value: enabled
  spgwc:
    label: omec-cp
    value: enabled

resources:
  enabled: true
  hss:
    requests:
      cpu: 2
      memory: 1Gi
    limits:
      cpu: 2
      memory: 1Gi
  mme:
    # Note that MME pod is composed of 4 containers
    # Provide resources for a container, not a pod total
    requests:
      cpu: 0.5
      memory: 1Gi
    limits:
      cpu: 0.5
      memory: 1Gi
  spgwc:
    requests:
      cpu: 2
      memory: 5Gi
    limits:
      cpu: 2
      memory: 5Gi

cassandra:
  deploy: true
  fullnameOverride: cassandra
  image:
    tag: 2.1.20
  #selector:
  #  nodeSelector:
  #    cassandra: enabled
  persistence:
    enabled: false
  config:
    #cluster_size: 1
    #seed_size: 1
    endpoint_snitch: GossipingPropertyFileSnitch
  readinessProbe:
    initialDelaySeconds: 10
  resources: {}
    #requests:
    #  memory: 4Gi
    #  cpu: 2
    #limits:
    #  memory: 4Gi
    #  cpu: 2

config:
  hss: {}
    # hssdb will be set to cassandra if unset
    #hssdb:
  mme:
    spgwAddr: spgwc-s11
    s11:
      nodePort:
        enabled: false
        port: 32124
    # appConfig is directly converted to config.json
    # See https://github.com/omec-project/openmme/blob/master/README.txt for more config options
    appConfig:
      mme:
        name: vmmestandalone
        group_id: 1
        code: 1
        mcc:
          dig1: 2
          dig2: 0
          dig3: 8
        mnc:
          dig1: 0
          dig2: 1
          dig3: -1
      s1ap:
        sctp_port: 36412
        sctp_port_external: 36412
      s11:
        egtp_default_port: 2123
        # sgw_addr and pgw_addr will be set dynamically if unset
        #sgw_addr:
        #pgw_addr:
      s6a:
        host_type: freediameter
        # host and realm will be set dynamically if unset
        #host:
        #realm:
  spgwc:
    apn: apn1
    ueIpPool:
      ip: 16.0.0.0
      mask: 255.0.0.0
    # This address must match to S1U IP address configured in omec-data-plane
    s1uAddr: 119.0.0.3
    # mmeAddr will be set automatically to mme pod IP if it's unset
    #mmeAddr:
    s11:
      nodePort:
        enabled: false
        port: 32123
    cpComm:
      nodePort:
        enabled: false
        port: 30021
    dpComm:
      # IMPORTANT: when you deploy CP and DP to separate clusters, enable nodePort
      # from both cpComm(omec-control-plane) and dpComm(omec-data-plane) and
      # set "addr" to remote cluster's entry node IP and
      # "port" to dpComm.nodePort.port value configured in omec-data-plane.
      addr: spgwu-dp-comm
      port: 20
    cfgFiles:
      # See https://github.com/omec-project/ngic-rtc/tree/master/config for details
      adc_rules.cfg: |
        [GLOBAL]
        NUM_ADC_RULES = 0
      meter_profile.cfg: |
        [GLOBAL]
        NUM_OF_IDX = 3

        [ENTRY_1]
        ; QCI5,QCI7 15.571kbps = 1947 B
        CIR = 2342400
        CBS = 5856
        EBS = 11712
        MTR_PROFILE_IDX = 5

        [ENTRY_2]
        ; QCI1, 44kbps = 5500 B
        CIR = 2342400
        CBS = 5856
        EBS = 11712
        MTR_PROFILE_IDX = 6

        [ENTRY_3]
        ; 128B, 2pps
        CIR = 2342400
        CBS = 512
        EBS = 1024
        MTR_PROFILE_IDX = 9
      pcc_rules.cfg: |
        [GLOBAL]
        NUM_PCC_FILTERS = 1
        UL_AMBR_MTR_PROFILE_IDX = 1
        DL_AMBR_MTR_PROFILE_IDX = 2

        [PCC_FILTER_1]
        RULE_NAME = DefaultRule
        RATING_GROUP = 9
        SERVICE_ID = 0
        RULE_STATUS = 0
        GATE_STATUS = 1
        SESSION_CONT = 0
        REPORT_LEVEL = 1
        CHARGING_MODE = 0
        METERING_METHOD = 0
        MUTE_NOTIFY = 0
        MONITORING_KEY = 0
        SPONSOR_ID = 0
        REDIRECT_INFO = 0
        PRECEDENCE = 254
        DROP_PKT_COUNT = 0
        UL_MBR_MTR_PROFILE_IDX = 3
        DL_MBR_MTR_PROFILE_IDX = 3
        SDF_FILTER_IDX = 99998
      sdf_rules.cfg: |
        [GLOBAL]
        NUM_SDF_FILTERS = 0
