# Copyright 2017-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  name: voltha
  namespace: {{ .Values.global.namespace }}
  serviceAccountName: {{ .Values.global.namespace }}-serviceaccount
  labels:
    name: voltha
spec:
  clusterIP: None
  ports:
    - name: rest
      port: 8882
      targetPort: 8882
    - name: mystery
      port: 8001
      targetPort: 8001
    - name: mystery2
      port: 8443
      targetPort: 8443
    - name: grpc
      port: 50555
      targetPort: 50555
  selector:
    app: voltha
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: voltha
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: voltha
    spec:
      serviceAccountName: {{ .Values.global.namespace }}-serviceaccount
      containers:
        - name: voltha
          image: {{ .Values.pull_docker_registry }}{{ .Values.images.envoy_for_etcd.repository }}:{{ .Values.images.envoy_for_etcd.tag }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "/usr/local/bin/envoyd"
            - "-envoy-cfg-template=/envoy/voltha-grpc-proxy.template.json"
            - "-envoy-config=/envoy/voltha-grpc-proxy.json"
            - "-kv=etcd"
            - "-kv-svc-name=etcd-cluster.default.svc.cluster.local"
            - "-kv-port=2379"
          ports:
            - containerPort: 8882
              name: rest-port
            - containerPort: 8001
              name: mystery-port
            - containerPort: 8443
              name: mystery2-port
            - containerPort: 50555
              name: grpc-port
          imagePullPolicy: {{ .Values.image_pull_policy }}


